# 👇 PARTE DE LOGIN
[credentials.usernames.admin]
name = "Administrador"
password = "12345"

[cookie]
name = "auth_cookie"
key = "minhachaveultrasecreta123"
expiry_days = 0.04



# 👇 PARTE DO GOOGLE SHEETS (não apague isso!)


[google_service_account]
type = "service_account"
project_id = "localizacao-produtos"
private_key_id = "779c1c41fccf78a0e755fb3569e328a26bafbd01"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2bCZ7AUqIgndz
+trbHlfJaq9Y3myDimNsNXlnrn3MCw4VE1stgGYpLtDrt9NgFiE9W4S4//6UCAEU
xItsQcjnnWwMKiI50y2tBvCh+3vk/6R7jNMOCwtvmOlCTRsJlWHeLkx3yD9fS2Z7
Cq53Z3OUO0HsLAZOW4YEf6Ne9sTucnJFnHo/xA8GmaOYskFUqEt3mdj9thIPd8QP
THzb/BpuEZu196QDj9oDVdTAGsuaZazXWGNWPvl31AlK6VPaEOEfawNxVZLeEldQ
KtT4WVAqz0fbu6xBj1urmR9TxuuEryryvyx/YUSmgJ3jCHM6O1cb0f0FsyCNpSyh
C0W6UGCdAgMBAAECggEABxnXzUnMKVsDbts+NIbZGHZOa+QWmcU5NbUG1uDINU6I
hmH/QTAXv0p6/Uil0f5H3h/8nzNEfpB+3ZyBUoi6Bb1klLxOzOzvQNETF18XIB93
uzZ3YGXQ1LqBTqB6k7QsqoMnXLH0Y498u6qQsYWwTlNt2hVkS8hiGQqQj7Raj0SK
OAf/FZSdf3Qs1Cb+VadPlZHVpp+CynENbdw3yutzZpPeLuQqSq3L/rxEvgwKgxcf
p36GPOHQsChqE7YaivKCPVRuNEakuI28yyYBYpZu7NwZ4XICxM5P/ikrPBnKvaeH
QvATwxIOUZUTGIpXj252kYhVLd5gS+eMZNGVn2lC0QKBgQDYmx3q65PGEkN11xyZ
Z2zBbvElN/V4w77kXnc0aV0tDDUrSFZyAl7BSpWd/G3m60k7kRA5MtMhUli7Lva/
Mfw07GaqHZjXy5kJDQUvazPXhPYtZjTowpiOFCZxe/Bevr7fZDIsKj8i3KDOTo5u
RDIejwut49NHAy3NubB+RiXBTQKBgQDXmX85w8psHrmuLdibbUFvmozd1wNQlsY1
Sg96jvqDpPwU5nLw4HGhAoPFtKctAZFs7C78rlmQt4v9X6x6T0hxT3DOf3aNpOvj
AipzpKnBeOFmXmxopdmHk0z5kC+TaPaACwRhZcSPDioaD627KPYHcAaromZeU0gA
OprmZTN0kQKBgA54PkVlO1ft/Gew2Q4+ZHt/h8huto08tlHXJatwpnLN7/dWO8Ad
/Gp5KwmExWq5qQi7phPMG2KMd7T5bC5Vjn2SlUEj/QPda/m4zvHd/XaWQUPDIiGy
bjJ/khnep64Mm/+cV+WvZMxVZMCjasxe7eIwuB0DrSd/RN4LW4jz8q25AoGAWjzO
uTivco1xnetma7dQ2gtPxlIF+ycAErHKxLsvMwZM09qYZSUrqf5JdOhlyDqNyY8Z
I30904pfN09h+1dPtM1RI7zJvAM5D6yKZBiZTHbxsEz5BtvTriEC6LlmkEYwVetG
jBVyLYX6LSo+xsUgJIDI6fFw8y3cRuxAhQn6fWECgYEAtTU9V7ZqzK1uFnMg1Gs2
SeTAqPJXJvU+CTiDDn9XBFzrqnrN2NF+zJrGr3wVU+1aYSbqBtXDLzsCZkiLBzMo
El5q0qCi5bWeI8AXLLcNGhlBJoN9RJi/Ld5F0JJ0FF5gbBlJ1hp1ljZho8E03j4R
CQdiccjQ4DlSdDWSHWSeBl0=
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheet-bot@localizacao-produtos.iam.gserviceaccount.com"
client_id = "104554515176641186053"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheet-bot@localizacao-produtos.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
